version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: academic_postgres
    environment:
      POSTGRES_DB: academic_portal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - academic_network
    restart: unless-stopped

  # Redis Cache (for session management and caching)
  redis:
    image: redis:7-alpine
    container_name: academic_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - academic_network
    restart: unless-stopped

  # FastAPI Backend (for development)
  backend:
    build: .
    container_name: academic_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/academic_portal
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - academic_network
    restart: unless-stopped

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: academic_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@academic-portal.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - academic_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  academic_network:
    driver: bridge