"""Add audit_logs table

Revision ID: d7a16712a8be
Revises: f93a4bb1bc5f
Create Date: 2025-11-16 10:15:13.740330+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a16712a8be'
down_revision: Union[str, Sequence[str], None] = 'f93a4bb1bc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('ANNOUNCEMENT', 'GRADE_POSTED', 'ENROLLMENT', 'ATTENDANCE', 'FEE_DUE', 'DOCUMENT_READY', 'MESSAGE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('announcements', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('announcements', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('announcements', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('announcements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_announcements_published', table_name='announcements')
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index(op.f('ix_announcements_is_published'), 'announcements', ['is_published'], unique=False)
    op.create_index(op.f('ix_announcements_publish_date'), 'announcements', ['publish_date'], unique=False)
    op.alter_column('assignments', 'course_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'max_points',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('assignments', 'weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('assignments', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_assignments_section', table_name='assignments')
    op.create_index(op.f('ix_assignments_course_section_id'), 'assignments', ['course_section_id'], unique=False)
    op.create_index(op.f('ix_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_is_published'), 'assignments', ['is_published'], unique=False)
    op.alter_column('attendance', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_index('idx_attendance_enrollment', table_name='attendance')
    op.drop_index('idx_attendance_enrollment_date', table_name='attendance')
    op.drop_index('idx_attendance_status', table_name='attendance')
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_enrollment_id'), 'attendance', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.drop_constraint('attendance_enrollment_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'enrollments', ['enrollment_id'], ['id'])
    op.alter_column('campuses', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('campuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_campuses_id'), 'campuses', ['id'], unique=False)
    op.alter_column('chat_participants', 'room_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('chat_participants', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('chat_participants', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('ADMIN', 'MODERATOR', 'MEMBER', name='participantrole'),
               existing_nullable=True)
    op.alter_column('chat_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_participants', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('chat_participants_room_id_user_id_key', 'chat_participants', type_='unique')
    op.create_index(op.f('ix_chat_participants_id'), 'chat_participants', ['id'], unique=False)
    op.create_unique_constraint('uq_room_user', 'chat_participants', ['room_id', 'user_id'])
    op.drop_constraint('chat_participants_user_id_fkey', 'chat_participants', type_='foreignkey')
    op.drop_constraint('chat_participants_room_id_fkey', 'chat_participants', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participants', 'chat_rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'chat_participants', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'chat_participants',
        existing_comment='Users participating in chat rooms',
        schema=None
    )
    op.alter_column('chat_rooms', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('COURSE', 'DIRECT', 'GROUP', 'AI_SUPPORT', name='roomtype'),
               existing_nullable=False)
    op.alter_column('chat_rooms', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'campus_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chat_rooms', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('chat_rooms_firebase_room_id_key', 'chat_rooms', type_='unique')
    op.drop_index('ix_chat_rooms_firebase_room_id', table_name='chat_rooms')
    op.create_index(op.f('ix_chat_rooms_firebase_room_id'), 'chat_rooms', ['firebase_room_id'], unique=True)
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.drop_table_comment(
        'chat_rooms',
        existing_comment='Chat room definitions',
        schema=None
    )
    op.alter_column('course_sections', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_sections', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_sections', 'max_students',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('course_sections', 'enrolled_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('course_sections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('course_sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_course_sections_active', table_name='course_sections')
    op.drop_index('idx_course_sections_course', table_name='course_sections')
    op.drop_index('idx_course_sections_instructor', table_name='course_sections')
    op.drop_index('idx_course_sections_semester', table_name='course_sections')
    op.create_index(op.f('ix_course_sections_course_id'), 'course_sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_sections_id'), 'course_sections', ['id'], unique=False)
    op.create_index(op.f('ix_course_sections_instructor_id'), 'course_sections', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_course_sections_semester_id'), 'course_sections', ['semester_id'], unique=False)
    op.create_unique_constraint('uq_section', 'course_sections', ['course_id', 'semester_id', 'section_code'])
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('courses_course_code_key', 'courses', type_='unique')
    op.drop_index('idx_courses_active', table_name='courses')
    op.drop_index('idx_courses_major', table_name='courses')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_major_id'), 'courses', ['major_id'], unique=False)
    op.alter_column('device_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('device_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('device_tokens', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.drop_table_comment(
        'device_tokens',
        existing_comment='Stores FCM device tokens for push notifications',
        schema=None
    )
    op.alter_column('document_requests', 'copies_requested',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('document_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('document_requests', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('document_requests', 'fee_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('document_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_document_requests_document_type', table_name='document_requests')
    op.drop_index('idx_document_requests_processed_by', table_name='document_requests')
    op.drop_index('idx_document_requests_status', table_name='document_requests')
    op.drop_index('idx_document_requests_student', table_name='document_requests')
    op.drop_index('ix_document_requests_result_document_id', table_name='document_requests')
    op.create_index(op.f('ix_document_requests_document_type'), 'document_requests', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_requests_id'), 'document_requests', ['id'], unique=False)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_index(op.f('ix_document_requests_student_id'), 'document_requests', ['student_id'], unique=False)
    op.drop_constraint('document_requests_result_document_id_fkey', 'document_requests', type_='foreignkey')
    op.drop_column('document_requests', 'result_document_id')
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.alter_column('enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'course_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('enrollments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('enrollments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_enrollments_section', table_name='enrollments')
    op.drop_index('idx_enrollments_section_status', table_name='enrollments')
    op.drop_index('idx_enrollments_status', table_name='enrollments')
    op.drop_index('idx_enrollments_student', table_name='enrollments')
    op.drop_index('idx_enrollments_student_section', table_name='enrollments')
    op.create_index(op.f('ix_enrollments_course_section_id'), 'enrollments', ['course_section_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_unique_constraint('uq_student_section', 'enrollments', ['student_id', 'course_section_id'])
    op.alter_column('fee_structures', 'campus_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('fee_structures', 'major_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('fee_structures', 'semester_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('fee_structures', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('fee_structures', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('fee_structures', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('fee_structures_id_seq'::regclass)"))
    op.create_index(op.f('ix_fee_structures_id'), 'fee_structures', ['id'], unique=False)
    op.drop_table_comment(
        'fee_structures',
        existing_comment='Fee structure definitions for campus/major/semester',
        schema=None
    )
    op.alter_column('grades', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'grade_value',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'max_grade',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_grades_approval_status', table_name='grades')
    op.drop_index('idx_grades_assignment', table_name='grades')
    op.drop_index('idx_grades_enrollment', table_name='grades')
    op.drop_index('ix_grades_assignment_id', table_name='grades')
    op.create_index(op.f('ix_grades_approval_status'), 'grades', ['approval_status'], unique=False)
    op.create_index(op.f('ix_grades_enrollment_id'), 'grades', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.drop_constraint('grades_enrollment_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_assignment_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'enrollments', ['enrollment_id'], ['id'])
    op.drop_column('grades', 'approved_at')
    op.drop_column('grades', 'assignment_id')
    op.alter_column('invoice_lines', 'invoice_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('invoice_lines', 'fee_structure_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('invoice_lines', 'qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoice_lines', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_invoice_lines_id'), 'invoice_lines', ['id'], unique=False)
    op.drop_table_comment(
        'invoice_lines',
        existing_comment='Line items for student invoices',
        schema=None
    )
    op.alter_column('invoices', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'issued_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_invoices_student', table_name='invoices')
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_semester_id'), 'invoices', ['semester_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_student_id'), 'invoices', ['student_id'], unique=False)
    op.alter_column('majors', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.alter_column('majors', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('majors', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('majors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('majors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('majors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_majors_id'), 'majors', ['id'], unique=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_payments_invoice', table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.drop_constraint('payments_invoice_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('roles', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='Business key for stable identification (STU, TCH, ADM, etc.)',
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_constraint('uq_roles_code', 'roles', type_='unique')
    op.drop_index('ix_roles_code', table_name='roles')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('section_schedules', sa.Column('day_of_week', sa.String(length=10), nullable=False))
    op.add_column('section_schedules', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('section_schedules', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('section_schedules', sa.Column('building', sa.String(length=100), nullable=True))
    op.alter_column('section_schedules', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('section_schedules', 'campus_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('section_schedules', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_section_schedules_section_start', table_name='section_schedules')
    op.create_index(op.f('ix_section_schedules_id'), 'section_schedules', ['id'], unique=False)
    op.drop_table_comment(
        'section_schedules',
        existing_comment='Stores class meeting schedules for course sections',
        schema=None
    )
    op.drop_column('section_schedules', 'start_ts')
    op.drop_column('section_schedules', 'canceled')
    op.drop_column('section_schedules', 'end_ts')
    op.alter_column('semesters', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('semesters', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('semesters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('semesters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.alter_column('student_sequences', 'major_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('student_sequences', 'campus_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('student_sequences', 'year_entered',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_sequences', 'last_sequence',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('student_sequences', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('student_sequences_id_seq'::regclass)"))
    op.drop_constraint('student_sequences_campus_id_year_key', 'student_sequences', type_='unique')
    op.create_index(op.f('ix_student_sequences_id'), 'student_sequences', ['id'], unique=False)
    op.drop_constraint('student_sequences_campus_id_fkey', 'student_sequences', type_='foreignkey')
    op.drop_column('student_sequences', 'sequence_number')
    op.drop_column('student_sequences', 'campus_id')
    op.drop_column('student_sequences', 'year')
    op.alter_column('support_tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_support_tickets_assigned_to'), 'support_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.alter_column('ticket_events', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ticket_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREATED', 'STATUS_CHANGE', 'ASSIGNMENT', 'COMMENT', 'RESOLUTION', name='eventtype'),
               existing_nullable=False)
    op.alter_column('ticket_events', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ticket_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_ticket_events_actor_id', table_name='ticket_events')
    op.create_index(op.f('ix_ticket_events_id'), 'ticket_events', ['id'], unique=False)
    op.drop_constraint('ticket_events_actor_id_fkey', 'ticket_events', type_='foreignkey')
    op.drop_constraint('ticket_events_ticket_id_fkey', 'ticket_events', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_events', 'support_tickets', ['ticket_id'], ['id'])
    op.drop_table_comment(
        'ticket_events',
        existing_comment='Audit log for support ticket changes',
        schema=None
    )
    op.drop_column('ticket_events', 'message')
    op.drop_column('ticket_events', 'actor_id')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_roles_user_id_role_id_campus_id_key', 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_campus_id'), 'user_roles', ['campus_id'], unique=False)
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_role_campus', 'user_roles', ['user_id', 'role_id', 'campus_id'])
    op.alter_column('username_sequences', 'base_username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('username_sequences', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('username_sequences', 'count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('username_sequences', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('username_sequences_id_seq'::regclass)"))
    op.drop_index('idx_username_sequences_lookup', table_name='username_sequences')
    op.drop_constraint('username_sequences_base_username_user_type_key', 'username_sequences', type_='unique')
    op.create_index(op.f('ix_username_sequences_id'), 'username_sequences', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_campus', table_name='users')
    op.drop_index('idx_users_major', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_constraint('unique_firebase_uid', 'users', type_='unique')
    op.drop_constraint('unique_username', 'users', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_firebase_uid_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_campus_id'), 'users', ['campus_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_major_id'), 'users', ['major_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('fk_users_campus', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_major', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_major', 'users', 'majors', ['major_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_campus', 'users', 'campuses', ['campus_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_major_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_campus_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_firebase_uid_key', 'users', ['firebase_uid'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('unique_username', 'users', ['username'])
    op.create_unique_constraint('unique_firebase_uid', 'users', ['firebase_uid'])
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_major', 'users', ['major_id'], unique=False)
    op.create_index('idx_users_campus', 'users', ['campus_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_username_sequences_id'), table_name='username_sequences')
    op.create_unique_constraint('username_sequences_base_username_user_type_key', 'username_sequences', ['base_username', 'user_type'])
    op.create_index('idx_username_sequences_lookup', 'username_sequences', ['base_username', 'user_type'], unique=False)
    op.alter_column('username_sequences', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('username_sequences_id_seq'::regclass)"))
    op.alter_column('username_sequences', 'count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('username_sequences', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('username_sequences', 'base_username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('uq_user_role_campus', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_campus_id'), table_name='user_roles')
    op.create_unique_constraint('user_roles_user_id_role_id_campus_id_key', 'user_roles', ['user_id', 'role_id', 'campus_id'])
    op.alter_column('user_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('ticket_events', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ticket_events', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'ticket_events',
        'Audit log for support ticket changes',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'ticket_events', type_='foreignkey')
    op.create_foreign_key('ticket_events_ticket_id_fkey', 'ticket_events', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ticket_events_actor_id_fkey', 'ticket_events', 'users', ['actor_id'], ['id'])
    op.drop_index(op.f('ix_ticket_events_id'), table_name='ticket_events')
    op.create_index('ix_ticket_events_actor_id', 'ticket_events', ['actor_id'], unique=False)
    op.alter_column('ticket_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ticket_events', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('ticket_events', 'event_type',
               existing_type=sa.Enum('CREATED', 'STATUS_CHANGE', 'ASSIGNMENT', 'COMMENT', 'RESOLUTION', name='eventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('ticket_events', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_to'), table_name='support_tickets')
    op.alter_column('support_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=True)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=True)
    op.alter_column('support_tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('student_sequences', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_sequences', sa.Column('campus_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('student_sequences', sa.Column('sequence_number', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_foreign_key('student_sequences_campus_id_fkey', 'student_sequences', 'campuses', ['campus_id'], ['id'])
    op.drop_index(op.f('ix_student_sequences_id'), table_name='student_sequences')
    op.create_unique_constraint('student_sequences_campus_id_year_key', 'student_sequences', ['campus_id', 'year'])
    op.alter_column('student_sequences', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('student_sequences_id_seq'::regclass)"))
    op.alter_column('student_sequences', 'last_sequence',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('student_sequences', 'year_entered',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_sequences', 'campus_code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('student_sequences', 'major_code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.alter_column('semesters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('semesters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('semesters', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('semesters', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.add_column('section_schedules', sa.Column('end_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('section_schedules', sa.Column('canceled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('section_schedules', sa.Column('start_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_table_comment(
        'section_schedules',
        'Stores class meeting schedules for course sections',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_section_schedules_id'), table_name='section_schedules')
    op.create_index('ix_section_schedules_section_start', 'section_schedules', ['section_id', 'start_ts'], unique=False)
    op.alter_column('section_schedules', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('section_schedules', 'campus_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('section_schedules', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('section_schedules', 'building')
    op.drop_column('section_schedules', 'end_time')
    op.drop_column('section_schedules', 'start_time')
    op.drop_column('section_schedules', 'day_of_week')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_index('ix_roles_code', 'roles', ['code'], unique=False)
    op.create_unique_constraint('uq_roles_code', 'roles', ['code'])
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Business key for stable identification (STU, TCH, ADM, etc.)',
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_invoice_id_fkey', 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index('idx_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'completed'::character varying"),
               existing_nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_majors_id'), table_name='majors')
    op.alter_column('majors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('majors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('majors', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('majors', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('majors', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('majors', 'code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_student_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_semester_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    op.create_index('idx_invoices_student', 'invoices', ['student_id'], unique=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'issued_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=True)
    op.alter_column('invoices', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table_comment(
        'invoice_lines',
        'Line items for student invoices',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_invoice_lines_id'), table_name='invoice_lines')
    op.alter_column('invoice_lines', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoice_lines', 'qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('invoice_lines', 'fee_structure_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('invoice_lines', 'invoice_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('grades', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_assignment_id_fkey', 'grades', 'assignments', ['assignment_id'], ['id'])
    op.create_foreign_key('grades_enrollment_id_fkey', 'grades', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_enrollment_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_approval_status'), table_name='grades')
    op.create_index('ix_grades_assignment_id', 'grades', ['assignment_id'], unique=False)
    op.create_index('idx_grades_enrollment', 'grades', ['enrollment_id'], unique=False)
    op.create_index('idx_grades_assignment', 'grades', ['assignment_name'], unique=False)
    op.create_index('idx_grades_approval_status', 'grades', ['approval_status'], unique=False)
    op.alter_column('grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('grades', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=True)
    op.alter_column('grades', 'weight',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'max_grade',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'grade_value',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table_comment(
        'fee_structures',
        'Fee structure definitions for campus/major/semester',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_fee_structures_id'), table_name='fee_structures')
    op.alter_column('fee_structures', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('fee_structures_id_seq'::regclass)"))
    op.alter_column('fee_structures', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('fee_structures', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'VND'::character varying"),
               existing_nullable=True)
    op.alter_column('fee_structures', 'semester_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('fee_structures', 'major_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('fee_structures', 'campus_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint('uq_student_section', 'enrollments', type_='unique')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_section_id'), table_name='enrollments')
    op.create_index('idx_enrollments_student_section', 'enrollments', ['student_id', 'course_section_id'], unique=False)
    op.create_index('idx_enrollments_student', 'enrollments', ['student_id'], unique=False)
    op.create_index('idx_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('idx_enrollments_section_status', 'enrollments', ['course_section_id', 'status'], unique=False)
    op.create_index('idx_enrollments_section', 'enrollments', ['course_section_id'], unique=False)
    op.alter_column('enrollments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('enrollments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'enrolled'::character varying"),
               existing_nullable=True)
    op.alter_column('enrollments', 'course_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.add_column('document_requests', sa.Column('result_document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_requests_result_document_id_fkey', 'document_requests', 'documents', ['result_document_id'], ['id'])
    op.drop_index(op.f('ix_document_requests_student_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_document_type'), table_name='document_requests')
    op.create_index('ix_document_requests_result_document_id', 'document_requests', ['result_document_id'], unique=False)
    op.create_index('idx_document_requests_student', 'document_requests', ['student_id'], unique=False)
    op.create_index('idx_document_requests_status', 'document_requests', ['status'], unique=False)
    op.create_index('idx_document_requests_processed_by', 'document_requests', ['processed_by'], unique=False)
    op.create_index('idx_document_requests_document_type', 'document_requests', ['document_type'], unique=False)
    op.alter_column('document_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'fee_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('document_requests', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('document_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('document_requests', 'copies_requested',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.create_table_comment(
        'device_tokens',
        'Stores FCM device tokens for push notifications',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.alter_column('device_tokens', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('device_tokens', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_courses_major_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_index('idx_courses_major', 'courses', ['major_id'], unique=False)
    op.create_index('idx_courses_active', 'courses', ['is_active'], unique=False)
    op.create_unique_constraint('courses_course_code_key', 'courses', ['course_code'])
    op.alter_column('courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_constraint('uq_section', 'course_sections', type_='unique')
    op.drop_index(op.f('ix_course_sections_semester_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_instructor_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_course_id'), table_name='course_sections')
    op.create_index('idx_course_sections_semester', 'course_sections', ['semester_id'], unique=False)
    op.create_index('idx_course_sections_instructor', 'course_sections', ['instructor_id'], unique=False)
    op.create_index('idx_course_sections_course', 'course_sections', ['course_id'], unique=False)
    op.create_index('idx_course_sections_active', 'course_sections', ['is_active'], unique=False)
    op.alter_column('course_sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_sections', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('course_sections', 'enrolled_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('course_sections', 'max_students',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=True)
    op.alter_column('course_sections', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course_sections', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table_comment(
        'chat_rooms',
        'Chat room definitions',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_firebase_room_id'), table_name='chat_rooms')
    op.create_index('ix_chat_rooms_firebase_room_id', 'chat_rooms', ['firebase_room_id'], unique=False)
    op.create_unique_constraint('chat_rooms_firebase_room_id_key', 'chat_rooms', ['firebase_room_id'])
    op.alter_column('chat_rooms', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_rooms', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'campus_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('chat_rooms', 'type',
               existing_type=sa.Enum('COURSE', 'DIRECT', 'GROUP', 'AI_SUPPORT', name='roomtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table_comment(
        'chat_participants',
        'Users participating in chat rooms',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.create_foreign_key('chat_participants_room_id_fkey', 'chat_participants', 'chat_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chat_participants_user_id_fkey', 'chat_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_room_user', 'chat_participants', type_='unique')
    op.drop_index(op.f('ix_chat_participants_id'), table_name='chat_participants')
    op.create_unique_constraint('chat_participants_room_id_user_id_key', 'chat_participants', ['room_id', 'user_id'])
    op.alter_column('chat_participants', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_participants', 'is_muted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chat_participants', 'role',
               existing_type=sa.Enum('ADMIN', 'MODERATOR', 'MEMBER', name='participantrole'),
               server_default=sa.text("'member'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('chat_participants', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chat_participants', 'room_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_campuses_id'), table_name='campuses')
    op.alter_column('campuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('campuses', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Asia/Ho_Chi_Minh'::character varying"),
               existing_nullable=True)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_enrollment_id_fkey', 'attendance', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_enrollment_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.create_index('idx_attendance_status', 'attendance', ['status'], unique=False)
    op.create_index('idx_attendance_enrollment_date', 'attendance', ['enrollment_id', 'date'], unique=False)
    op.create_index('idx_attendance_enrollment', 'attendance', ['enrollment_id'], unique=False)
    op.create_index('idx_attendance_date', 'attendance', ['date'], unique=False)
    op.alter_column('attendance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'present'::character varying"),
               existing_nullable=True)
    op.alter_column('attendance', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_assignments_is_published'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_due_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_section_id'), table_name='assignments')
    op.create_index('idx_assignments_section', 'assignments', ['course_section_id'], unique=False)
    op.alter_column('assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assignments', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('assignments', 'weight',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('assignments', 'max_points',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('assignments', 'course_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_announcements_publish_date'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_published'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.create_index('idx_announcements_published', 'announcements', ['is_published', 'publish_date'], unique=False)
    op.alter_column('announcements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('announcements', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('announcements', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('announcements', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
